import os
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Dict, Any
import markdown

logger = logging.getLogger(__name__)

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
FROM_NAME = os.getenv("FROM_NAME", "Sales Insight Automator")


def build_html_email(summary: str, filename: str, stats: Dict[str, Any]) -> str:
    """Convert markdown summary to styled HTML email."""
    total_rev = stats.get("total_revenue", 0)
    total_units = stats.get("total_units_sold", 0)
    rows = stats.get("total_rows", 0)

    # Convert markdown to HTML
    try:
        summary_html = markdown.markdown(summary, extensions=["nl2br"])
    except Exception:
        summary_html = summary.replace("\n", "<br>")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 0; padding: 0; background: #f4f6f9; }}
  .container {{ max-width: 680px; margin: 40px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }}
  .header {{ background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%); padding: 40px 32px; color: white; }}
  .header h1 {{ margin: 0 0 8px; font-size: 24px; font-weight: 700; }}
  .header p {{ margin: 0; opacity: 0.75; font-size: 14px; }}
  .metrics {{ display: flex; padding: 24px 32px; background: #f8fafc; border-bottom: 1px solid #e2e8f0; gap: 16px; }}
  .metric {{ flex: 1; text-align: center; }}
  .metric-value {{ font-size: 28px; font-weight: 700; color: #0f172a; }}
  .metric-label {{ font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 4px; }}
  .content {{ padding: 32px; color: #334155; line-height: 1.7; font-size: 15px; }}
  .content h2 {{ color: #0f172a; font-size: 18px; margin: 24px 0 12px; padding-bottom: 8px; border-bottom: 2px solid #e2e8f0; }}
  .content ul {{ padding-left: 20px; }}
  .content li {{ margin-bottom: 6px; }}
  .footer {{ background: #f8fafc; padding: 20px 32px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; }}
  .badge {{ display: inline-block; background: #dbeafe; color: #1d4ed8; padding: 4px 10px; border-radius: 20px; font-size: 12px; font-weight: 600; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>📊 Sales Intelligence Report</h1>
    <p>AI-Generated Executive Summary &nbsp;·&nbsp; <span class="badge" style="background:rgba(255,255,255,0.15);color:white;">{filename}</span></p>
  </div>
  <div class="metrics">
    <div class="metric">
      <div class="metric-value">${total_rev:,.0f}</div>
      <div class="metric-label">Total Revenue</div>
    </div>
    <div class="metric">
      <div class="metric-value">{total_units:,}</div>
      <div class="metric-label">Units Sold</div>
    </div>
    <div class="metric">
      <div class="metric-value">{rows}</div>
      <div class="metric-label">Records</div>
    </div>
  </div>
  <div class="content">
    {summary_html}
  </div>
  <div class="footer">
    Generated by <strong>Sales Insight Automator</strong> &nbsp;·&nbsp; Rabbitt AI &nbsp;·&nbsp; Powered by Google Gemini
  </div>
</div>
</body>
</html>"""
    return html


async def send_summary_email(
    recipient_email: str,
    summary: str,
    filename: str,
    stats: Dict[str, Any]
) -> None:
    """Send the AI summary via SMTP."""
    if not SMTP_USER or not SMTP_PASSWORD:
        logger.warning(f"[MOCK EMAIL] Would send to {recipient_email}:\n{summary[:200]}...")
        return

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"📊 Sales Insight Report – {filename}"
        msg["From"] = f"{FROM_NAME} <{SMTP_USER}>"
        msg["To"] = recipient_email

        # Plain text fallback
        plain_text = MIMEText(summary, "plain")
        msg.attach(plain_text)

        # HTML version
        html_content = build_html_email(summary, filename, stats)
        html_part = MIMEText(html_content, "html")
        msg.attach(html_part)

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, recipient_email, msg.as_string())

        logger.info(f"Email sent successfully to {recipient_email}")

    except smtplib.SMTPException as e:
        logger.error(f"SMTP error sending to {recipient_email}: {e}")
        raise RuntimeError(f"Email delivery failed: {str(e)}")
    except Exception as e:
        logger.error(f"Unexpected error sending email: {e}")
        raise
